import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import dynamic from "next/dynamic";
const ToastProvider = dynamic(() => import('./layoutComponents/ToastProvider'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Icon Zambia",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const session = await auth();

  return (
    <html lang="en" >
      <body className={inter.className} >
        <ToastProvider>
          <SessionProvider session={session} refetchInterval={60 * 60 * 24 * 1}>
            {children}
          </SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
